services:
  - type: web
    name: cropguard-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "3"
